version: 2

jobs:
  ubuntu:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - run: apt update -qq && apt install -y make dvipsmk git texlive-lang-japanese
      - checkout
      - run: make
  nix-shell:
    docker:
      - image: "nixos/nix"
    steps:
      - run: nix-env -i git
      - checkout
      - run: nix-shell shell.nix --command 'exit 0'

workflows:
  version: 2
  build:
    jobs:
      - "ubuntu"
      - "nix-shell"
