version: 2

jobs:
  nix-shell:
    docker:
      - image: "nixos/nix"
    steps:
      - nix-env -i git
      - checkout
      - run: nix-shell shell.nix --command 'exit 0'

workflows:
  version: 2
  build:
    jobs:
      - "nix-shell"
